# Generated by Django 4.1.1 on 2023-03-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_remove_medicalhistory_patient_patient_allergies_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Patients',
        ),
    ]
