# Generated by Django 4.1.1 on 2023-03-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_rename_patient_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
