# Generated by Django 4.1.1 on 2023-03-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_alter_patients_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
