# Generated by Django 4.1.1 on 2022-11-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_update_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details_user',
            name='user',
        ),
    ]
