# Generated by Django 4.1.1 on 2023-03-30 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_payment_alter_patients_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
