# Generated by Django 4.1.1 on 2023-04-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
