# Generated by Django 4.1.1 on 2022-11-23 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_details_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details_doctor',
            name='user',
        ),
        migrations.AlterField(
            model_name='details_doctor',
            name='doc_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home_app.doctors'),
        ),
    ]
