# Generated by Django 4.1.1 on 2023-04-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0009_remove_booking_patient_name_booking_booked_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='health_issues',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='hospitalizations',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='supplements',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='surgeries',
        ),
        migrations.AddField(
            model_name='patients',
            name='asthma',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='b_complex',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='biotin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='cancer_systemic_disease',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='coenzyme',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='epilepsy_seizure',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='folic_acid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='heart_disease',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='high_blood_pressure',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='hormone_imbalance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='kidney_disease',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='liver_disease',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='melatonin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='multivitamin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='omega3',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='other_health_conditions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='other_supplements',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='thyroid_disorder',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='vitamin3',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='vitamin_d',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='zinc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='previous_report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
