# Generated by Django 4.1.1 on 2023-04-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0010_remove_patients_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_user',
        ),
    ]
