# Generated by Django 4.1.1 on 2023-04-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0011_remove_booking_booked_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='asthma',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='b_complex',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='biotin',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='cancer_systemic_disease',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='coenzyme',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='epilepsy_seizure',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='folic_acid',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='heart_disease',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='high_blood_pressure',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='hormone_imbalance',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='kidney_disease',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='liver_disease',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='melatonin',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='multivitamin',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='omega3',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='other_health_conditions',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='other_supplements',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='thyroid_disorder',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='vitamin3',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='vitamin_d',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='zinc',
        ),
        migrations.AddField(
            model_name='patients',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='beverages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='claustrophobic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='health_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='pain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='photo1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='photo2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='photo3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='smoker',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='supplements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='previous_report',
            field=models.FileField(blank=True, null=True, upload_to='previous_reports/'),
        ),
    ]
