# Generated by Django 4.1.1 on 2023-04-17 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0012_remove_patients_asthma_remove_patients_b_complex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_app.customuser'),
        ),
    ]
