# Generated by Django 4.1.1 on 2023-04-17 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0013_appointment_booked_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_app.customuser'),
        ),
    ]
