# Generated by Django 4.1.1 on 2023-05-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0021_supplement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='past_medical_history',
            new_name='beverages',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='dental_image1',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='dental_image2',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='dental_image3',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='is_smoker',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='patients',
            name='allergies',
            field=models.CharField(blank=True, choices=[('Aspirin', 'Aspirin'), ('Shellfish', 'Shellfish'), ('Tree Nuts', 'Tree Nuts'), ('Iodine', 'Iodine'), ('Latex', 'Latex'), ('Dairy', 'Dairy'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Other', 'Other'), ('None', 'None')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='claustrophobic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='health_issues',
            field=models.CharField(blank=True, choices=[('Hormone Imbalance', 'Hormone Imbalance'), ('Asthma', 'Asthma'), ('Cancer/Systemic disease', 'Cancer/Systemic disease'), ('Epilepsy/Seizure', 'Epilepsy/Seizure'), ('High Blood Pressure', 'High Blood Pressure'), ('Diabetes', 'Diabetes'), ('Heart Problems', 'Heart Problems'), ('HIV/AIDS', 'HIV/AIDS'), ('Auto immune Disorder', 'Auto immune Disorder'), ('Depression', 'Depression'), ('HeadAches/Migrations', 'HeadAches/Migrations'), ('Other', 'Other'), ('None', 'None')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='pain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='photo1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='photo2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='photo3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='previous_report',
            field=models.FileField(blank=True, null=True, upload_to='previous_reports/'),
        ),
        migrations.AddField(
            model_name='patients',
            name='smoker',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O-', 'O-'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=6, null=True),
        ),
        migrations.RemoveField(
            model_name='patients',
            name='supplements',
        ),
        migrations.DeleteModel(
            name='Supplement',
        ),
        migrations.AddField(
            model_name='patients',
            name='supplements',
            field=models.CharField(blank=True, choices=[('Multivitamin', 'Multivitamin'), ('Omega3', 'Omega3'), ('Vitamin3', 'Vitamin3'), ('BComplex', 'BComplex'), ('Vitamin D/D3', 'Vitamin D/D3'), ('Zinc', 'Zinc'), ('Folic Acid', 'Folic Acid'), ('Melatonin', 'Melatonin'), ('Biotin', 'Biotin'), ('Coenzyme', 'Coenzyme'), ('None', 'None'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
