# Generated by Django 4.1.1 on 2023-05-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0022_rename_past_medical_history_patients_beverages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='beverages',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='claustrophobic',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='pain',
            field=models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='smoker',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=50, null=True),
        ),
    ]
